### PR TITLE
Remove `content-encoding` header

### LINKED ISSUE #28: content-encoding header should be removed
Return of this function is instance of http.IncomingMessage 
The problem is that this function does not delete content-encoding header, so the result is that you have an IncomingMessage object with content-encoding header with original value like 'gzip' but the stream is no longer compressed.

I think the the function should also delete content-encoding header before returning the result stream

### PR DESCRIPTION
**Pull request by binary-person**
this should fix #28

### CODE REVIEW

**Comment by sindresorhus** [comment]
You need to update the types too.

**Comment by binary-person** [comment]
that would be a breaking change as one would need to export the types as well for the user and `index.test-d.ts`, so code that used to be
```js
const decompressResponse = require('decompress-response');
```
would need to be rewritten as
```js
const decompressResponse = require('decompress-response').decompressResponse;
```
is it alright for that to happen?

**Comment by sindresorhus** [comment]
You can still use a `module.exports`. You just put the type in a `namespace`: https://github.com/sindresorhus/typescript-definition-style-guide#documentation

**Comment by binary-person** [comment]
alright, thanks! I'm still pretty new to typescript, and wasn't familiar with the idea of namespaces. can you check the commit out?

**Comment by sindresorhus** [comment]
Would be better to use the `Omit` type.

**Comment by binary-person** [comment]
I've tried before with `Omit` but since node's `http.d.ts`'s `IncomingHttpHeaders` extends `NodeJS.Dict<string | string[]>`, the resulting type when used with `Omit` is `[x: string]: string | string[]; [x: number]: string | string[];`

**Comment by sindresorhus** [comment]
Does it work better with https://github.com/sindresorhus/type-fest/blob/main/source/except.d.ts (just copy-paste it in)? If not, what you have is fine.

**Comment by binary-person** [comment]
no, it doesn't work. it yields the same problem with `Omit`, with the resulting type being `[x: string]: string | string[]; [x: number]: string | string[];`

**Pull request merged**
